using System.Security;
using System.Text;
using System.IO;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using SkiaSharp;
using A = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;
using P = DocumentFormat.OpenXml.Presentation;
using W = DocumentFormat.OpenXml.Wordprocessing;

namespace Snapture.App.Services;

/// <summary>Exports Step Capture sessions to editable Word and PowerPoint documents.</summary>
public static class StepCaptureOfficeExporter
{
    private const long EmusPerInch = 914400;
    private const long DocxMaxWidth = 6_500_000;
    private const long DocxMaxHeight = 8_800_000;
    private const long SlideWidth = 12_192_000;
    private const long SlideHeight = 6_858_000;

    public static string ExportDocx(string outputPath, string title, IEnumerable<StepCaptureExporter.StepEntry> entries)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);
        var items = entries?.ToList() ?? throw new ArgumentNullException(nameof(entries));
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);

        using var document = WordprocessingDocument.Create(
            outputPath,
            WordprocessingDocumentType.Document);
        var mainPart = document.AddMainDocumentPart();
        var body = new W.Body();
        mainPart.Document = new W.Document(body);

        body.Append(CreateWordParagraph(title, "36", bold: true));
        body.Append(CreateWordParagraph(
            $"Generated by Snapture · {DateTime.Now:yyyy-MM-dd HH:mm} · {items.Count} steps",
            "20",
            bold: false));

        uint drawingId = 1;
        foreach (var entry in items)
        {
            body.Append(CreateWordParagraph($"Step {entry.Number}", "28", bold: true));
            AppendWordCaption(body, entry.Caption);
            AppendWordInputTrack(body, entry);
            var dimensions = ReadImageDimensions(entry.FilePath);
            if (dimensions is null) continue;

            var imagePart = mainPart.AddImagePart(GetImagePartType(entry.FilePath));
            using (var stream = File.OpenRead(entry.FilePath))
                imagePart.FeedData(stream);

            var size = FitInside(dimensions.Value.Width, dimensions.Value.Height, DocxMaxWidth, DocxMaxHeight);
            var drawing = CreateWordImageDrawing(
                mainPart.GetIdOfPart(imagePart),
                size.Width,
                size.Height,
                drawingId++,
                $"Step {entry.Number}");
            body.Append(new W.Paragraph(new W.Run(drawing)));
        }

        body.Append(new W.SectionProperties(
            new W.PageSize { Width = 12240, Height = 15840 },
            new W.PageMargin { Top = 720, Right = 720, Bottom = 720, Left = 720 }));
        mainPart.Document.Save();
        return outputPath;
    }

    public static string ExportPptx(string outputPath, string title, IEnumerable<StepCaptureExporter.StepEntry> entries)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);
        var items = entries?.ToList() ?? throw new ArgumentNullException(nameof(entries));
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);

        using var document = PresentationDocument.Create(
            outputPath,
            PresentationDocumentType.Presentation);
        var presentationPart = document.AddPresentationPart();
        var masterPart = presentationPart.AddNewPart<SlideMasterPart>("rIdMaster");
        var layoutPart = masterPart.AddNewPart<SlideLayoutPart>("rIdLayout");
        var themePart = masterPart.AddNewPart<ThemePart>("rIdTheme");
        layoutPart.AddPart(masterPart, "rIdMaster");

        WritePart(masterPart, CreateSlideMasterXml());
        WritePart(layoutPart, CreateSlideLayoutXml());
        WritePart(themePart, CreateThemeXml());

        var presentation = new P.Presentation
        {
            SlideMasterIdList = new P.SlideMasterIdList(
                new P.SlideMasterId
                {
                    Id = 2_147_483_648U,
                    RelationshipId = presentationPart.GetIdOfPart(masterPart)
                }),
            SlideIdList = new P.SlideIdList(),
            SlideSize = new P.SlideSize { Cx = (int)SlideWidth, Cy = (int)SlideHeight },
            NotesSize = new P.NotesSize { Cx = 6_858_000, Cy = 9_144_000 }
        };
        presentationPart.Presentation = presentation;

        AddSlide(
            presentationPart,
            layoutPart,
            presentation.SlideIdList!,
            title,
            $"Step Capture · {items.Count} steps · Generated by Snapture",
            imagePath: null,
            slideNumber: 1);

        uint slideNumber = 2;
        foreach (var entry in items)
        {
            AddSlide(
                presentationPart,
                layoutPart,
                presentation.SlideIdList!,
                $"Step {entry.Number}",
                BuildOfficeCaption(entry),
                entry.FilePath,
                slideNumber++);
        }

        presentationPart.Presentation.Save();
        return outputPath;
    }

    private static void AddSlide(
        PresentationPart presentationPart,
        SlideLayoutPart layoutPart,
        P.SlideIdList slideIds,
        string title,
        string? caption,
        string? imagePath,
        uint slideNumber)
    {
        var slidePart = presentationPart.AddNewPart<SlidePart>();
        slidePart.AddPart(layoutPart, "rIdLayout");

        string? imageRelationship = null;
        ImageDimensions? dimensions = null;
        var sourcePath = imagePath;
        if (sourcePath is not null && File.Exists(sourcePath))
        {
            dimensions = ReadImageDimensions(sourcePath);
            if (dimensions is not null)
            {
                var imagePart = slidePart.AddImagePart(GetImagePartType(sourcePath), "rIdImage");
                using var stream = File.OpenRead(sourcePath);
                imagePart.FeedData(stream);
                imageRelationship = slidePart.GetIdOfPart(imagePart);
            }
        }

        WritePart(slidePart, CreateSlideXml(title, caption, imageRelationship, dimensions, slideNumber));
        slideIds.Append(new P.SlideId
        {
            Id = 255U + slideNumber,
            RelationshipId = presentationPart.GetIdOfPart(slidePart)
        });
    }

    private static W.Paragraph CreateWordParagraph(string text, string fontSize, bool bold)
    {
        var properties = new W.RunProperties();
        if (bold) properties.AppendChild(new W.Bold());
        properties.AppendChild(new W.FontSize { Val = fontSize });
        return new W.Paragraph(new W.Run(properties, new W.Text(text ?? string.Empty)));
    }

    private static void AppendWordCaption(W.Body body, string? caption)
    {
        if (string.IsNullOrWhiteSpace(caption)) return;
        foreach (var line in caption.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
            body.Append(CreateWordParagraph(line, "22", bold: false));
    }

    private static void AppendWordInputTrack(W.Body body, StepCaptureExporter.StepEntry entry)
    {
        var track = StepCaptureInputFormatter.FormatOfficeCaption(entry.Keystrokes, entry.Clicks);
        if (track is not null)
            body.Append(CreateWordParagraph(track, "18", bold: false));
    }

    private static string? BuildOfficeCaption(StepCaptureExporter.StepEntry entry)
    {
        var track = StepCaptureInputFormatter.FormatOfficeCaption(entry.Keystrokes, entry.Clicks);
        if (string.IsNullOrWhiteSpace(entry.Caption))
            return track;
        if (track is null)
            return entry.Caption;
        return $"{entry.Caption.Trim()}\n{track}";
    }

    private static W.Drawing CreateWordImageDrawing(
        string relationshipId,
        long width,
        long height,
        uint drawingId,
        string name)
    {
        return new W.Drawing(
            new DW.Inline(
                new DW.Extent { Cx = width, Cy = height },
                new DW.EffectExtent
                {
                    LeftEdge = 0,
                    TopEdge = 0,
                    RightEdge = 0,
                    BottomEdge = 0
                },
                new DW.DocProperties { Id = drawingId, Name = name },
                new DW.NonVisualGraphicFrameDrawingProperties(
                    new A.GraphicFrameLocks { NoChangeAspect = true }),
                new A.Graphic(
                    new A.GraphicData(
                        new PIC.Picture(
                            new PIC.NonVisualPictureProperties(
                                new PIC.NonVisualDrawingProperties { Id = drawingId, Name = name },
                                new PIC.NonVisualPictureDrawingProperties()),
                            new PIC.BlipFill(
                                new A.Blip { Embed = relationshipId },
                                new A.Stretch(new A.FillRectangle())),
                            new PIC.ShapeProperties(
                                new A.Transform2D(
                                    new A.Offset { X = 0, Y = 0 },
                                    new A.Extents { Cx = width, Cy = height }),
                                new A.PresetGeometry(new A.AdjustValueList())
                                {
                                    Preset = A.ShapeTypeValues.Rectangle
                                })))
                    {
                        Uri = "http://schemas.openxmlformats.org/drawingml/2006/picture"
                    })));
    }

    private static string CreateSlideMasterXml() =>
        """
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
          <p:cSld name="Snapture Master">
            <p:spTree>
              <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
              <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
            </p:spTree>
          </p:cSld>
          <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
          <p:sldLayoutIdLst><p:sldLayoutId id="2147483648" r:id="rIdLayout"/></p:sldLayoutIdLst>
          <p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles>
        </p:sldMaster>
        """;

    private static string CreateSlideLayoutXml() =>
        """
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1">
          <p:cSld name="Blank">
            <p:spTree>
              <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
              <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
            </p:spTree>
          </p:cSld>
          <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
        </p:sldLayout>
        """;

    private static string CreateThemeXml() =>
        """
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Snapture Theme">
          <a:themeElements>
            <a:clrScheme name="Snapture">
              <a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1>
              <a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1>
              <a:dk2><a:srgbClr val="1F2430"/></a:dk2>
              <a:lt2><a:srgbClr val="F4F5F7"/></a:lt2>
              <a:accent1><a:srgbClr val="7C3AED"/></a:accent1>
              <a:accent2><a:srgbClr val="2563EB"/></a:accent2>
              <a:accent3><a:srgbClr val="059669"/></a:accent3>
              <a:accent4><a:srgbClr val="D97706"/></a:accent4>
              <a:accent5><a:srgbClr val="DB2777"/></a:accent5>
              <a:accent6><a:srgbClr val="0891B2"/></a:accent6>
              <a:hlink><a:srgbClr val="2563EB"/></a:hlink>
              <a:folHlink><a:srgbClr val="7C3AED"/></a:folHlink>
            </a:clrScheme>
            <a:fontScheme name="Snapture">
              <a:majorFont><a:latin typeface="Aptos Display"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont>
              <a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont>
            </a:fontScheme>
            <a:fmtScheme name="Snapture">
              <a:fillStyleLst>
                <a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill>
                <a:solidFill><a:srgbClr val="F4F5F7"/></a:solidFill>
                <a:solidFill><a:srgbClr val="E5E7EB"/></a:solidFill>
              </a:fillStyleLst>
              <a:lnStyleLst>
                <a:ln w="9525"><a:solidFill><a:srgbClr val="7C3AED"/></a:solidFill><a:prstDash val="solid"/></a:ln>
                <a:ln w="25400"><a:solidFill><a:srgbClr val="2563EB"/></a:solidFill><a:prstDash val="solid"/></a:ln>
                <a:ln w="38100"><a:solidFill><a:srgbClr val="059669"/></a:solidFill><a:prstDash val="solid"/></a:ln>
              </a:lnStyleLst>
              <a:effectStyleLst>
                <a:effectStyle><a:effectLst><a:outerShdw blurRad="0" dist="0" dir="0" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="0"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle>
                <a:effectStyle><a:effectLst><a:outerShdw blurRad="0" dist="0" dir="0" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="0"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle>
                <a:effectStyle><a:effectLst><a:outerShdw blurRad="0" dist="0" dir="0" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="0"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle>
              </a:effectStyleLst>
              <a:bgFillStyleLst>
                <a:solidFill><a:srgbClr val="FFFFFF"/></a:solidFill>
                <a:solidFill><a:srgbClr val="F4F5F7"/></a:solidFill>
                <a:solidFill><a:srgbClr val="E5E7EB"/></a:solidFill>
              </a:bgFillStyleLst>
            </a:fmtScheme>
          </a:themeElements>
        </a:theme>
        """;

    private static string CreateSlideXml(
        string title,
        string? caption,
        string? imageRelationship,
        ImageDimensions? dimensions,
        uint slideNumber)
    {
        var titleShape = CreateTextShapeXml(
            2,
            "Title",
            457200,
            228600,
            11_277_600,
            600_000,
            title,
            2800,
            bold: true);
        var captionShape = string.IsNullOrWhiteSpace(caption)
            ? string.Empty
            : CreateTextShapeXml(
                3,
                "Caption",
                457200,
                900000,
                11_277_600,
                650000,
                caption,
                1800,
                bold: false);
        var imageShape = imageRelationship is not null && dimensions is not null
            ? CreatePictureXml(imageRelationship, dimensions.Value, 4)
            : string.Empty;

        return $"""
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
          <p:cSld name="Step {slideNumber}">
            <p:spTree>
              <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
              <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
              {titleShape}
              {captionShape}
              {imageShape}
            </p:spTree>
          </p:cSld>
          <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
        </p:sld>
        """;
    }

    private static string CreateTextShapeXml(
        uint id,
        string name,
        long x,
        long y,
        long width,
        long height,
        string? text,
        int fontSize,
        bool bold)
    {
        var paragraphs = string.Join(
            string.Empty,
            (text ?? string.Empty)
                .Replace("\r\n", "\n", StringComparison.Ordinal)
                .Split('\n')
                .Select(line =>
                    $"<a:p><a:r><a:rPr lang=\"en-US\" sz=\"{fontSize}\"{(bold ? " b=\"1\"" : string.Empty)}/><a:t xml:space=\"preserve\">{EscapeXml(line)}</a:t></a:r><a:endParaRPr lang=\"en-US\"/></a:p>"));
        return $"""
        <p:sp>
          <p:nvSpPr><p:cNvPr id="{id}" name="{EscapeXml(name)}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>
          <p:spPr><a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{width}" cy="{height}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
          <p:txBody><a:bodyPr wrap="square" anchor="t"/><a:lstStyle/>{paragraphs}</p:txBody>
        </p:sp>
        """;
    }

    private static string CreatePictureXml(string relationshipId, ImageDimensions dimensions, uint id)
    {
        var size = FitInside(dimensions.Width, dimensions.Height, 11_277_600, 4_950_000);
        var x = (SlideWidth - size.Width) / 2;
        var y = 1_650_000;
        return $"""
        <p:pic>
          <p:nvPicPr><p:cNvPr id="{id}" name="Step image"/><p:cNvPicPr preferRelativeResize="0"/><p:nvPr/></p:nvPicPr>
          <p:blipFill><a:blip r:embed="{relationshipId}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill>
          <p:spPr><a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{size.Width}" cy="{size.Height}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        </p:pic>
        """;
    }

    private static void WritePart(OpenXmlPart part, string xml)
    {
        using var stream = part.GetStream(FileMode.Create, FileAccess.Write);
        using var writer = new StreamWriter(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        writer.Write(xml.Trim());
    }

    private static string EscapeXml(string value) =>
        SecurityElement.Escape(value) ?? string.Empty;

    private static PartTypeInfo GetImagePartType(string path) =>
        Path.GetExtension(path).ToLowerInvariant() switch
        {
            ".jpg" or ".jpeg" => ImagePartType.Jpeg,
            ".gif" => ImagePartType.Gif,
            ".bmp" => ImagePartType.Bmp,
            _ => ImagePartType.Png
        };

    private static ImageDimensions? ReadImageDimensions(string path)
    {
        try
        {
            using var bitmap = SKBitmap.Decode(path);
            return bitmap is null || bitmap.Width <= 0 || bitmap.Height <= 0
                ? null
                : new ImageDimensions(bitmap.Width, bitmap.Height);
        }
        catch
        {
            return null;
        }
    }

    private static ImageDimensions FitInside(int width, int height, long maxWidth, long maxHeight)
    {
        var scale = Math.Min((double)maxWidth / width, (double)maxHeight / height);
        return new ImageDimensions(
            Math.Max(1, (int)Math.Round(width * scale)),
            Math.Max(1, (int)Math.Round(height * scale)));
    }

    private readonly record struct ImageDimensions(int Width, int Height);
}
