# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: SysAdminDoc.Snapture
PackageVersion: 0.6.0
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: Snapture.App.exe
    PortableCommandAlias: snapture
Scope: user
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - snapture
ReleaseDate: 2026-05-08
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/SysAdminDoc/Snapture/releases/download/v0.6.0/Snapture-v0.6.0-win-x64.zip
    # Pulled from the published release SHA256SUMS file at v0.6.0.
    InstallerSha256: 11aa4fe7a43888eba1005840c5d5831f56a7f34c63f0bde96d5eedf68f35b6ef
ManifestType: installer
ManifestVersion: 1.9.0
